name: cd

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: nested
    environment: pypi
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
      - run: uv build
      - run: uv publish --trusted-publishing always
