name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ruff-check:
    runs-on: nested
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
      - run: uvx ruff@latest check

  ruff-format:
    runs-on: nested
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
      - run: uvx ruff@latest format --check

  basedpyright:
    runs-on: nested
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - run: uv sync
      - run: uvx basedpyright@latest

  pytest:
    runs-on: nested
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - run: uv sync
      - run: uv run pytest -q
